In [8]:
import numpy as np

a1=np.array([1,2,3,4])
print(a1[2])
a0=np.zeros((2,2))
print(a0)
print(a1)


3
[[0. 0.]
 [0. 0.]]
[1 2 3 4]


In [11]:
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr[2:4])
print(arr[::3])

[30 40]
[10 40]


In [12]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


print(x + y)    # add
print(x - y)    # subtract
print(x * y)    # multiply
print(x / y)    # divide

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
import numpy as np

a = np.array([-3, -1, 0, 1, 3]) # array with both positive and negative values

# Applying a unary operation: absolute value
print(np.absolute(a))

[3 1 0 1 3]


In [18]:
import numpy as np

# Two example arrays
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# Applying a binary operation: addition
res = np.add(a1, a2)
print(res)

[5 7 9]


In [19]:
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))

# exponential values
b = np.array([0, 1, 2, 3])
print(np.exp(b))
print(np.sqrt(b))

# square root of array values
print (np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         1.25331414 1.77245385]


In [21]:
import numpy as np

dtype = [('name', 'S10'), ('year', int), ('cgpa', float)]
vals  = [('Hrithik', 2009, 8.5),
         ('Ajay',    2008, 8.7),
         ('Pankaj',  2008, 7.9),
         ('Aakash',  2009, 9.0)]

a = np.array(vals, dtype=dtype)

print(np.sort(a, order='name'))
print(np.sort(a, order=['year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [ ]:
# Que 1) Implement program using numpy array to add two arrays.

In [22]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)


[ 7  9 11 13 15]


In [ ]:
# Que 2)Implement program for scalar operation using numpy array

In [27]:
import numpy as np
s1=np.array([12,13,14,15])
print(s1+10)
print(s1-10)
print(s1*3)
print(s1/5)
print(s1//5)

[22 23 24 25]
[2 3 4 5]
[36 39 42 45]
[2.4 2.6 2.8 3. ]
[2 2 2 3]


In [29]:
# Que 3) Implement program to execute any 4 universal array function'''

In [30]:
import numpy as np
p1=np.array([1,2,3,4,5])
p2=np.array([6,7,8,9,10])
p3=np.array([1,4,9,16,25])


print(np.add(p1,p2))
print("min",np.min(p1))
print("max",np.max(p1))
print("mean",np.mean(p1))
print("Square :",np.sqrt(p3))
print("Square:",np.square(p1))

[ 7  9 11 13 15]
min 1
max 5
mean 3.0
Square : [1. 2. 3. 4. 5.]
Square: [ 1  4  9 16 25]
